---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          readinessProbe:
            tcpSocket:
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
