---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/service-internal

labels:
  - includeSelectors: true
    pairs:
      service: test-app2

patches:
  - target:
      name: my_service
    patch: |-
      - op: replace
        path: /metadata/name
        value: test-app2
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe/httpGet
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe/httpGet
  - path: deployment.yaml

replacements:
  - path: ../common/internal/replacement.yaml

images:
  - name: my_service
    newName: 1234567890.dkr.ecr.us-east-1.amazonaws.com/test-app2
